"""
build_index.py — Stage 0 (ingest / index-time)

Parses the Vulcan OmniPro 220 owner's manual into a typed knowledge graph.
Each node carries STRUCTURE (pages, table/image counts -> modality) detected
from the PDF, plus a SEMANTIC layer (summary, keywords, answerable questions)
that in production is generated by an LLM at ingest time and here is curated +
grounded against the extracted page text.

Output: index.json  ->  { nodes: [...], edges: [...] }

The whole point: the index is small enough (~2-3k tokens) to hand to a CHEAP
routing model at query time. The heavy content (full pages, rasterized
diagrams) is loaded only AFTER routing decides which nodes are relevant.
"""

import json, re, sys
from pathlib import Path
import pdfplumber

MANUAL = Path("challenge/files/owner-manual.pdf")

# --- 1. Section map, lifted from the manual's printed Table of Contents (p1) ---
#     (start_page, end_page) inclusive, 1-indexed to match printed page numbers.
SECTIONS = [
    ("safety",      "Safety",                         2,  6),
    ("specs",       "Specifications",                 7,  7),
    ("controls",    "Controls",                       8,  9),
    ("mig",         "MIG / Flux-Cored Wire Welding", 10, 23),
    ("tig",         "TIG / Stick Welding",           24, 33),
    ("tips",        "Welding Tips",                  34, 40),
    ("maintenance", "Maintenance",                   41, 45),
    ("parts",       "Parts List and Diagram",        46, 47),
    ("warranty",    "Warranty",                      48, 48),
]

# --- 2. Notable ASSET nodes: the table/diagram/photo/schematic content a
#        text-only RAG would miss. page = anchor page in the PDF. ---
#   modality: text | table | diagram | photo | schematic | matrix
ASSETS = [
    # id, parent_section, title, page, modality, keywords, answers
    ("duty_cycle_table", "specs", "Duty Cycle Matrix (MIG/TIG/Stick, 120V & 240V)", 7, "table",
     ["duty cycle", "amperage", "200a", "240v", "120v", "overheat", "rated", "thermal"],
     ["What's the duty cycle for MIG at 200A on 240V?",
      "How long can I weld before it overheats at 150A?"]),
    ("controls_panel", "controls", "Front Panel / LCD Synergic Controls", 8, "diagram",
     ["control", "lcd", "knob", "panel", "synergic", "display", "setting"],
     ["What does each knob on the front do?"]),
    ("mig_wire_setup", "mig", "MIG Wire Spool Installation & Wire Feed Path", 10, "diagram",
     ["spool", "wire", "install", "feed", "door latch", "wingnut", "liner", "load wire"],
     ["How do I load the wire spool?"]),
    ("wire_feed_tension", "mig", "Drive Roll & Tensioner Calibration", 19, "diagram",
     ["tension", "drive roll", "tensioner", "wire feed", "slipping", "birdnest", "pressure"],
     ["My wire keeps birdnesting / slipping — what tension?"]),
    ("mig_polarity", "mig", "MIG vs Flux-Cored Polarity & Cable Sockets", 11, "diagram",
     ["polarity", "dcen", "dcep", "electrode positive", "socket", "ground clamp", "flux-cored", "gas"],
     ["What polarity for flux-cored vs gas MIG? Which socket?"]),
    ("tig_polarity", "tig", "TIG/Stick Polarity & Ground Clamp Socket", 24, "diagram",
     ["polarity", "tig", "stick", "dcen", "ground clamp", "socket", "torch", "electrode negative"],
     ["What polarity setup for TIG? Which socket does the ground clamp go in?"]),
    ("penetration_control", "tips", "Workpiece Heat / Weld Penetration Control", 35, "table",
     ["penetration", "heat", "ctwd", "travel speed", "current", "thickness", "burn-through"],
     ["My welds aren't penetrating — what do I change?"]),
    ("weld_diagnosis", "tips", "Weld Diagnosis Photos (porosity, voltage, speed, polarity)", 35, "photo",
     ["porosity", "weld defect", "diagnosis", "voltage too high", "travel speed", "wrong polarity",
      "bad weld", "spatter", "undercut"],
     ["I'm getting porosity in my flux-cored welds. What should I check?",
      "Why does my bead look like this?"]),
    ("troubleshooting", "maintenance", "Troubleshooting Matrix", 42, "matrix",
     ["troubleshoot", "error", "no arc", "won't feed", "fault", "problem", "not working", "overheating"],
     ["The welder won't strike an arc — what now?"]),
    ("wiring_schematic", "maintenance", "Electrical Wiring Schematic", 45, "schematic",
     ["wiring", "schematic", "electrical", "rectifier", "circuit", "hall", "transformer", "cn1"],
     ["Where does this wire go on the board?"]),
    ("parts_diagram", "parts", "Exploded Parts Diagram & Parts List", 46, "diagram",
     ["parts", "replacement", "exploded", "assembly", "part number", "spare"],
     ["What's the part number for the drive roll?"]),
]

# --- 3. Cross-reference edges: typed relations that turn a flat TOC into a
#        graph. These mirror real cross-references in the manual (e.g. p35
#        lists "wrong polarity" and "wire feed too fast" as weld defects). ---
#   (src, dst, relation)
CROSS_EDGES = [
    ("weld_diagnosis", "mig_polarity",      "cause_of"),
    ("weld_diagnosis", "tig_polarity",      "cause_of"),
    ("weld_diagnosis", "wire_feed_tension", "cause_of"),
    ("weld_diagnosis", "penetration_control","related"),
    ("penetration_control", "duty_cycle_table", "related"),
    ("troubleshooting", "duty_cycle_table", "related"),     # overheating -> duty cycle
    ("troubleshooting", "wire_feed_tension", "related"),
    ("troubleshooting", "mig_polarity",     "related"),
    ("mig_wire_setup",  "wire_feed_tension","prerequisite"),
    ("mig_polarity",    "mig_wire_setup",   "prerequisite"),
    ("duty_cycle_table","specs",            "part_of"),
    ("parts_diagram",   "wiring_schematic", "related"),
]

STOP = set("the a an of to and or for with on in is be are this that your you it if "
           "before use using do not then from at as by per up off out".split())


def extract(manual):
    """Pull per-page structure (table/image counts) + text from the PDF."""
    pages = {}
    with pdfplumber.open(manual) as pdf:
        for i, pg in enumerate(pdf.pages, start=1):
            txt = (pg.extract_text() or "")
            pages[i] = {
                "text": txt,
                "n_tables": len(pg.extract_tables()),
                "n_images": len(pg.images),
            }
    return pages


def top_keywords(text, k=8):
    words = re.findall(r"[a-z][a-z\-]{3,}", text.lower())
    freq = {}
    for w in words:
        if w in STOP:
            continue
        freq[w] = freq.get(w, 0) + 1
    return [w for w, _ in sorted(freq.items(), key=lambda x: -x[1])[:k]]


def page_range_text(pages, a, b):
    return "\n".join(pages[p]["text"] for p in range(a, b + 1) if p in pages)


def build():
    pages = extract(MANUAL)
    nodes, edges = [], []

    # Section nodes (the coarse routing layer)
    for sid, title, a, b in SECTIONS:
        body = page_range_text(pages, a, b)
        n_tab = sum(pages[p]["n_tables"] for p in range(a, b + 1) if p in pages)
        n_img = sum(pages[p]["n_images"] for p in range(a, b + 1) if p in pages)
        nodes.append({
            "id": sid, "type": "section", "title": title,
            "pages": [a, b], "modality": "text",
            "has_tables": n_tab > 0, "has_images": n_img > 2,
            "auto_keywords": top_keywords(body),
            "summary": f"{title}: manual pages {a}-{b}.",
        })

    # Asset nodes (the fine routing layer — what makes answers multimodal)
    for aid, parent, title, page, modality, kws, answers in ASSETS:
        grounded = top_keywords(pages.get(page, {}).get("text", ""), 6)
        nodes.append({
            "id": aid, "type": "asset", "title": title,
            "pages": [page, page], "modality": modality,
            "parent": parent,
            "keywords": kws,
            "auto_keywords": grounded,
            "answers": answers,
            "summary": title,
        })
        edges.append({"src": parent, "dst": aid, "rel": "contains"})

    # Same-process clustering (helps multi-hop within a process)
    for a, b in [("mig_wire_setup", "mig_polarity"),
                 ("mig_polarity", "wire_feed_tension")]:
        edges.append({"src": a, "dst": b, "rel": "same_process"})

    # Cross-reference edges
    for s, d, r in CROSS_EDGES:
        edges.append({"src": s, "dst": d, "rel": r})

    # Every process/asset implicitly requires safety (prerequisite hub)
    for sid in ["mig", "tig", "maintenance"]:
        edges.append({"src": sid, "dst": "safety", "rel": "prerequisite"})

    index = {
        "product": "Vulcan OmniPro 220 (Harbor Freight #57812)",
        "source": "owner-manual.pdf (48 pages)",
        "nodes": nodes,
        "edges": edges,
    }
    Path("index.json").write_text(json.dumps(index, indent=2))
    print(f"Wrote index.json: {len(nodes)} nodes, {len(edges)} edges")
    # quick modality census
    from collections import Counter
    c = Counter(n["modality"] for n in nodes if n["type"] == "asset")
    print("Asset modalities:", dict(c))


if __name__ == "__main__":
    build()
